routes/web.php
<?php

use App\Http\Controllers\DaftarTransaksiController;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\DashboardController;
use App\Http\Controllers\LoginController;
use App\Http\Controllers\UserController;
use App\Http\Controllers\MasterBarangController;
use App\Http\Controllers\TransaksiController;

use App\Http\Livewire\DaftarTransaksi;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Route::group(['middleware' => ['guest']], function(){
    Route::get('/', [LoginController::class, 'index'])->name('login');
    Route::get('/login', [LoginController::class, 'index'])->name('login');
    Route::post('/login', [LoginController::class, 'authenticate'])->name('login');
});

Route::group(['middleware' => ['auth']], function(){
    Route::post('/logout', [LoginController::class, 'logout'])->name('logout');
    Route::resource('dashboard', DashboardController::class);

    Route::resource('transaksi', TransaksiController::class);
    Route::resource('daftar-transaksi', DaftarTransaksiController::class);
    Route::get('cetak/{id}', [DaftarTransaksiController::class, 'print'])->name('cetak');
});

Route::group(['middleware' => ['auth', 'role:admin']], function(){
    Route::resource('user', UserController::class);
    Route::resource('master-barang', MasterBarangController::class);
});

Route::get('/error', function () {
    return view('error');
});

app/Models/MasterBarang.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class MasterBarang extends Model
{
    use HasFactory;

    protected $guarded = ['id'];

    public function transaksiPembelianBarang(){
        return $this->hasMany(TransaksiPembelianBarang::class);
    }
}

app/Http/Controllers/MasterBarangController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Models\MasterBarang;
use RealRashid\SweetAlert\Facades\Alert;

class MasterBarangController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        // jika menggunakan datatable
        $masterBarang = MasterBarang::latest()->get();
        // dd($masterBarang);

        //jika menggunakan table biasa
        //$masterBarang = MasterBarang::latest()->paginate(5);

        return view('page.master-barang.index', compact('masterBarang'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
            'nama_barang' => 'required|unique:master_barangs,nama_barang',
            'harga_satuan' => 'required|numeric',
            'jumlah' => 'required|numeric'
        ],[
            'nama_barang.required' => 'Nama barang tidak boleh kosong',
            'nama_barang.unique' => 'Nama barang sudah tersedia',
            'harga_satuan.required' => 'Harga satuan tidak boleh kosong',
            'harga_satuan.numeric' => 'Harga satuan harus berupa Angka',
            'jumlah.required' => 'Stok tidak boleh kosong',
            'jumlah.numeric' => 'Stok harus berupa Angka'
        ]);

        $masterBarang = new MasterBarang;
        $masterBarang->nama_barang = $request->nama_barang;
        $masterBarang->harga_satuan = $request->harga_satuan;
        $masterBarang->jumlah = $request->jumlah;
        $masterBarang->save();

        Alert::success('Berhasil!', 'Data barang berhasil ditambahkan')->autoClose(3000);
        return back();

    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        // dd($request->all());
        $request->validate([
            'harga_satuan' => 'required|numeric',
            'jumlah' => 'required|numeric'
        ],[
            'harga_satuan.required' => 'Harga satuan tidak boleh kosong',
            'harga_satuan.numeric' => 'Harga satuan harus berupa Angka',
            'jumlah.required' => 'Stok tidak boleh kosong',
            'jumlah.numeric' => 'Stok harus berupa Angka'
        ]);

        $masterBarang = MasterBarang::find($id);

        if($request->nama_barang != $masterBarang->nama_barang){
            $request->validate([
                'nama_barang' => 'required|unique:master_barangs,nama_barang',
            ],[
                'nama_barang.required' => 'Nama barang tidak boleh kosong',
                'nama_barang.unique' => 'Nama barang sudah tersedia'
            ]);
        }

        $masterBarang->nama_barang = $request->nama_barang;
        $masterBarang->harga_satuan = $request->harga_satuan;
        $masterBarang->jumlah = $request->jumlah;
        $masterBarang->save();

        Alert::success('Berhasil!', 'Data barang berhasil di edit')->autoClose(3000);
        return back();

    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $masterBarang = MasterBarang::find($id);

        $masterBarang->delete();

        Alert::success('Berhasil!', 'Data barang berhasil di Hapus')->autoClose(3000);

        return back();
    }
}

resources/views/page/master-barang/index.blade.php
@extends('layouts.app')

@section('title', 'Master Barang')

@section('content')
<!-- Begin Page Content -->
<div class="container-fluid">

    <!-- Page Heading -->
    <h1 class="h3 mb-2 text-gray-800">Master Barang</h1>
    <p class="mb-4">Berikut merupakan data Master Barang</p>
    <button class="btn btn-primary mb-2" data-toggle="modal" data-target="#modalCreate">Tambah Data Barang</button>
    <!-- DataTales Example -->
    <div class="card shadow mb-4">
        <div class="card-header py-3">
            <h6 class="m-0 font-weight-bold text-primary">Table Master Barang</h6>
        </div>
        <div class="card-body">
            <div class="table-responsive">
                <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                    <thead>
                        <tr>
                            <th class="text-center" style="width: 5%">No</th>
                            <th class="text-center" style="width: 30%">Nama Barang</th>
                            <th class="text-center" style="width: 15%">Harga Sastuan</th>
                            <th class="text-center" style="width: 10%">Stok</th>
                            <th class="text-center" style="width: 15%">Tanggal Dibuat</th>
                            <th class="text-center" style="width: 25%">Action</th>
                        </tr>
                    </thead>
                    <tbody>
                        @forelse ($masterBarang as $key => $data )
                        <tr>
                            <td class="text-center">{{ $key + 1 }}</td>
                            <td>{{ $data->nama_barang }}</td>
                            <td class="text-right">Rp. {{number_format($data->harga_satuan,0,',','.')  }}</td>
                            <td class="text-center">{{ $data->jumlah }} pcs</td>
                            <td>{{ Carbon\Carbon::parse($data->created_at)->translatedFormat('l, d F Y H:i') }}</td>
                            <td class="text-center">
                                <div class="form-inline justify-content-center">
                                    <button class="btn btn-primary btn-sm mr-1" data-toggle="modal"
                                        data-target="#modalEdit-{{ $data->id }}">Edit</button>
                                    <form action="{{ route('master-barang.destroy', $data->id) }}" method="POST">
                                        @csrf
                                        @method('DELETE')
                                        {{-- <a href="{{ route('master-barang.show', $data->id) }}" class="btn btn-info
                                        btn-sm">Detail</a> --}}
                                        <input type="submit" class="btn btn-danger my-1 btn-sm show_confirm"
                                            value="Delete">
                                    </form>
                                </div>
                            </td>
                        </tr>
                        @empty
                        <tr>
                            <td colspan="4" class="text-center text-danger">Data Kosong !</td>
                        </tr>
                        @endforelse
                    </tbody>
                </table>

            </div>
        </div>
    </div>
</div>
<!-- /.container-fluid -->

<!-- Modal create-->
<div class="modal fade" id="modalCreate" data-backdrop="static" tabindex="-1" role="dialog"
    aria-labelledby="staticBackdropLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="staticBackdropLabel">Tambah Barang</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <form action="{{ route('master-barang.store') }}" method="post">
                <div class="modal-body">
                    @csrf
                    <div class="card-body">
                        <div class="form-group">
                            <label for="nama_barang">Nama Barang</label>
                            <input type="text" name="nama_barang"
                                class="form-control @error('nama_barang') is-invalid @enderror" id="nama_barang"
                                value="{{ old('nama_barang') }}">
                            @error('nama_barang')
                            <div class="invalid-feedback">{{ $message }}</div>
                            @enderror
                        </div>
                        <div class="form-group">
                            <label for="harga_satuan">Harga Satuan</label>
                            <input type="number" name="harga_satuan"
                                class="form-control @error('harga_satuan') is-invalid @enderror" id="harga_satuan"
                                value="{{ old('harga_satuan') }}">
                            @error('harga_satuan')
                            <div class="invalid-feedback">{{ $message }}</div>
                            @enderror
                        </div>
                        <div class="form-group">
                            <label for="jumlah">Stok</label>
                            <input type="number" name="jumlah"
                                class="form-control @error('jumlah') is-invalid @enderror" id="jumlah"
                                value="{{ old('jumlah') }}">
                            @error('jumlah')
                            <div class="invalid-feedback">{{ $message }}</div>
                            @enderror
                        </div>
                    </div>
                    <!-- /.card-body -->
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                    <button type="submit" class="btn btn-primary">Simpan</button>
                </div>
            </form>
        </div>
    </div>
</div>

<!-- Modal Edit-->
@foreach ($masterBarang as $dta )
<div class="modal fade" id="modalEdit-{{ $dta->id }}" data-backdrop="static" tabindex="-1" role="dialog"
    aria-labelledby="staticBackdropLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="staticBackdropLabel">Edit Barang</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <form action="{{ route('master-barang.update', $dta->id) }}" method="post">
                <div class="modal-body">
                    @csrf
                    @method('PUT')
                    <div class="card-body">
                        <div class="form-group">
                            <label for="nama_barang">Nama Barang</label>
                            <input type="text" name="nama_barang"
                                class="form-control @error('nama_barang') is-invalid @enderror" id="nama_barang"
                                value="{{ old('nama_barang', $dta->nama_barang) }}">
                            @error('nama_barang')
                            <div class="invalid-feedback">{{ $message }}</div>
                            @enderror
                        </div>
                        <div class="form-group">
                            <label for="harga_satuan">Harga Satuan</label>
                            <input type="number" name="harga_satuan"
                                class="form-control @error('harga_satuan') is-invalid @enderror" id="harga_satuan"
                                value="{{ old('harga_satuan', $dta->harga_satuan) }}">
                            @error('harga_satuan')
                            <div class="invalid-feedback">{{ $message }}</div>
                            @enderror
                        </div>
                        <div class="form-group">
                            <label for="jumlah">Stok</label>
                            <input type="number" name="jumlah"
                                class="form-control @error('jumlah') is-invalid @enderror" id="jumlah"
                                value="{{ old('jumlah', $dta->jumlah) }}">
                            @error('jumlah')
                            <div class="invalid-feedback">{{ $message }}</div>
                            @enderror
                        </div>
                    </div>
                    <!-- /.card-body -->
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                    <button type="submit" class="btn btn-primary">Update</button>
                </div>
            </form>
        </div>
    </div>
</div>
@endforeach

@endsection

resources/views/page/master-barang/indexTableBisasa.blade.php
@extends('layouts.app')

@section('title', 'Master Barang')

@section('content')
<!-- Begin Page Content -->
<div class="container-fluid">

    <!-- Page Heading -->
    <h1 class="h3 mb-2 text-gray-800">Master Barang</h1>
    <p class="mb-4">Berikut merupakan data Master Barang</p>
    <button class="btn btn-primary mb-2" data-toggle="modal" data-target="#modalCreate">Tambah Data Barang</button>
    <!-- DataTales Example -->
    <div class="card shadow mb-4">
        <div class="card-header py-3">
            <h6 class="m-0 font-weight-bold text-primary">Table Master Barang</h6>
        </div>
        <div class="card-body">
            <div class="table-responsive">
                <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                    <thead>
                        <tr>
                            <th class="text-center" style="width: 5%">No</th>
                            <th class="text-center" style="width: 35%">Nama Barang</th>
                            <th class="text-center" style="width: 20%">Harga Sastuan</th>
                            <th class="text-center" style="width: 15%">Tanggal Dibuat</th>
                            <th class="text-center" style="width: 25%">Action</th>
                        </tr>
                    </thead>
                    <tbody>
                        @forelse ($masterBarang as $key => $data )
                        <tr>
                            <td class="text-center">{{ $masterBarang->firstItem() + $key }}</td>
                            <td>{{ $data->nama_barang }}</td>
                            <td class="text-right">Rp. {{number_format($data->harga_satuan,0,',','.')  }}</td>
                            <td>{{ Carbon\Carbon::parse($data->created_at)->translatedFormat('l, d F Y H:i') }}</td>
                            <td class="text-center">
                                <div class="form-inline justify-content-center">
                                    <button class="btn btn-primary btn-sm mr-1" data-toggle="modal"
                                        data-target="#modalEdit-{{ $data->id }}">Edit</button>
                                    <form action="{{ route('master-barang.destroy', $data->id) }}" method="POST">
                                        @csrf
                                        @method('DELETE')
                                        {{-- <a href="{{ route('master-barang.show', $data->id) }}" class="btn btn-info
                                        btn-sm">Detail</a> --}}
                                        <input type="submit" class="btn btn-danger my-1 btn-sm show_confirm"
                                            value="Delete">
                                    </form>
                                </div>
                            </td>
                        </tr>
                        @empty
                        <tr>
                            <td colspan="4" class="text-center text-danger">Data Kosong !</td>
                        </tr>
                        @endforelse
                    </tbody>
                </table>
                <div class="pull-left">
                    Showing
                    {{ $masterBarang->firstItem() }}
                    To
                    {{ $masterBarang->lastItem() }}
                    of
                    {{ $masterBarang->total() }}
                    {{-- TOTAL tidak bisa digunakan ketika pake simplePaginate--}}
                    entries
                </div>
                <div class="col float-right">
                    <div class="pagination-block float-right">
                        {{-- hapus class pagination-block, jika menggunakan simplePaginate --}}
                        {{-- hapus isi didalam kurung links, jika menggunakan simplePaginate --}}

                        {{ $masterBarang->links('layouts.paginate.paginationlinks') }}
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- /.container-fluid -->

<!-- Modal create-->
<div class="modal fade" id="modalCreate" data-backdrop="static" tabindex="-1" role="dialog"
    aria-labelledby="staticBackdropLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="staticBackdropLabel">Tambah Barang</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <form action="{{ route('master-barang.store') }}" method="post">
                <div class="modal-body">
                    @csrf
                    <div class="card-body">
                        <div class="form-group">
                            <label for="nama_barang">Nama Barang</label>
                            <input type="text" name="nama_barang"
                                class="form-control @error('nama_barang') is-invalid @enderror" id="nama_barang"
                                value="{{ old('nama_barang') }}">
                            @error('nama_barang')
                            <div class="invalid-feedback">{{ $message }}</div>
                            @enderror
                        </div>
                        <div class="form-group">
                            <label for="harga_satuan">Harga Satuan</label>
                            <input type="number" name="harga_satuan"
                                class="form-control @error('harga_satuan') is-invalid @enderror" id="harga_satuan"
                                value="{{ old('harga_satuan') }}">
                            @error('harga_satuan')
                            <div class="invalid-feedback">{{ $message }}</div>
                            @enderror
                        </div>
                    </div>
                    <!-- /.card-body -->
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                    <button type="submit" class="btn btn-primary">Simpan</button>
                </div>
            </form>
        </div>
    </div>
</div>

<!-- Modal Edit-->
@foreach ($masterBarang as $dta )
<div class="modal fade" id="modalEdit-{{ $dta->id }}" data-backdrop="static" tabindex="-1" role="dialog"
    aria-labelledby="staticBackdropLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="staticBackdropLabel">Edit Barang</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <form action="{{ route('master-barang.update', $dta->id) }}" method="post">
                <div class="modal-body">
                    @csrf
                    @method('PUT')
                    <div class="card-body">
                        <div class="form-group">
                            <label for="nama_barang">Nama Barang</label>
                            <input type="text" name="nama_barang"
                                class="form-control @error('nama_barang') is-invalid @enderror" id="nama_barang"
                                value="{{ old('nama_barang', $dta->nama_barang) }}">
                            @error('nama_barang')
                            <div class="invalid-feedback">{{ $message }}</div>
                            @enderror
                        </div>
                        <div class="form-group">
                            <label for="harga_satuan">Harga Satuan</label>
                            <input type="number" name="harga_satuan"
                                class="form-control @error('harga_satuan') is-invalid @enderror" id="harga_satuan"
                                value="{{ old('harga_satuan', $dta->harga_satuan) }}">
                            @error('harga_satuan')
                            <div class="invalid-feedback">{{ $message }}</div>
                            @enderror
                        </div>
                    </div>
                    <!-- /.card-body -->
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                    <button type="submit" class="btn btn-primary">Update</button>
                </div>
            </form>
        </div>
    </div>
</div>
@endforeach

@endsection