routes/web.php
<?php

use App\Http\Controllers\DaftarTransaksiController;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\DashboardController;
use App\Http\Controllers\LoginController;
use App\Http\Controllers\UserController;
use App\Http\Controllers\MasterBarangController;
use App\Http\Controllers\TransaksiController;

use App\Http\Livewire\DaftarTransaksi;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Route::group(['middleware' => ['guest']], function(){
    Route::get('/', [LoginController::class, 'index'])->name('login');
    Route::get('/login', [LoginController::class, 'index'])->name('login');
    Route::post('/login', [LoginController::class, 'authenticate'])->name('login');
});

Route::group(['middleware' => ['auth']], function(){
    Route::post('/logout', [LoginController::class, 'logout'])->name('logout');
    Route::resource('dashboard', DashboardController::class);

    Route::resource('transaksi', TransaksiController::class);
    Route::resource('daftar-transaksi', DaftarTransaksiController::class);
    Route::get('cetak/{id}', [DaftarTransaksiController::class, 'print'])->name('cetak');
});

Route::group(['middleware' => ['auth', 'role:admin']], function(){
    Route::resource('user', UserController::class);
    Route::resource('master-barang', MasterBarangController::class);
});

Route::get('/error', function () {
    return view('error');
});

app/Http/Controllers/DaftarTransaksiController.php
<?php

namespace App\Http\Controllers;

use Carbon\Carbon;
use Illuminate\Http\Request;
use App\Models\TransaksiPembelian;
use App\Models\TransaksiPembelianBarang;
use PDF;

class DaftarTransaksiController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
        $daftarTransaksi = "";
        if (auth()->user()->role == "kasir") {
            # code...
            $daftarTransaksi = TransaksiPembelian::whereDate('created_at', Carbon::today())->latest()->get();
        }else{
            $daftarTransaksi = TransaksiPembelian::latest()->get();
        }

        return view('page.daftar-transaksi.index', compact('daftarTransaksi'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
        $totalHarga = TransaksiPembelian::find($id);
        $daftarTransaksi = TransaksiPembelianBarang::where('transaksi_pembelian_id', $id)->get();
        return view('page.daftar-transaksi.detail', compact('daftarTransaksi', 'totalHarga'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }

    public function print($id)
    {
        # code...
        $dataTransaksi = TransaksiPembelianBarang::where('transaksi_pembelian_id', $id)->get();
        $totalHarga = TransaksiPembelian::find($id);
        $data = [
            'title' => 'Data Transaksi Kasir SIPD JABAR',
            'date' => 'Tanggal Cetak: '.date('d/m/Y'),
            'dataTransaksi' => $dataTransaksi,
            'totalHarga' => $totalHarga
        ];

        // dd($data);
        $pdf = PDF::loadView('page.daftar-transaksi.print', $data);
        return $pdf->stream();
    }


}

app/Http/Livewire/DaftarTransaksi.php
<?php

namespace App\Http\Livewire;

use Livewire\Component;
use App\Models\TransaksiPembelian;

class DaftarTransaksi extends Component
{
    public $daftarTransaksi;
    public $date;
    public $ulala = "Data";

    public function dateFilter()
    {
        # code...
        $this->ulala = "Ganti";
    }

    public function mount()
    {
        # code...
        $this->daftarTransaksi = TransaksiPembelian::latest()->get();
        $this->ulala = "Data";
    }
    public function render()
    {
        
        return view('livewire.daftar-transaksi', [
            'dataTransaksi' => $this->daftarTransaksi
        ]);
    }
}

resources/views/page/daftar-transaksi/detail.blade.php
@extends('layouts.app')

@section('title', 'Master Barang')

@section('content')

<a href="{{ route('daftar-transaksi.index') }}" class="btn btn-primary mb-3">Kembali</a>
    <div class="card shadow mb-4">
        <div class="card-header py-3">
            <h6 class="m-0 font-weight-bold text-primary" >Tabel Data Transaksi</h6>
        </div>
        <div class="card-body">
            <div class="table-responsive">
                <table id="dataTable" class="table table-bordered" style="width:100%">
                    <thead>
                        <tr>
                            <th class="text-center">No</th>
                            <th class="text-center">Waktu Pembelian</th>
                            <th class="text-center">Nama Barang</th>
                            <th class="text-center">Jumlah</th>
                            <th class="text-center">Harga Satuan</th>
                            <th class="text-center">Total</th>

                        </tr>
                    </thead>
                    <tbody>
                        @foreach ($daftarTransaksi as $key => $data )
                            <tr>
                                <td class="text-center">{{ $key + 1 }}</td>
                                <td>{{ Carbon\Carbon::parse($data->created_at)->translatedFormat('l, d F Y H:i') }}</td>
                                <td>{{ $data->masterBarang->nama_barang }}</td>
                                <td class="text-center">{{ $data->jumlah }}</td>
                                <td class="text-right">Rp  {{number_format($data->masterBarang->harga_satuan,0,',','.')  }}</td>
                                <td class="text-right">Rp {{ number_format($data->jumlah * $data->masterBarang->harga_satuan,0,',','.') }} </td>
                            </tr>
                        @endforeach
                    </tbody>
                    <tfoot>
                        <tr>
                            <td class="text-center font-weight-bold" colspan="5"> Total Transaksi</td>
                            <td class="text-right font-weight-bold">Rp {{ number_format($totalHarga->total_harga,0,',','.') }}</td>
                        </tr>
                    </tfoot>
                </table>
            </div>
        </div>
    </div>

    {{-- @foreach ($daftarTransaksi as $dta )
        <div class="modal fade" id="modalEdit-{{ $dta->id }}" data-backdrop="static" tabindex="-1" role="dialog" aria-labelledby="staticBackdropLabel" aria-hidden="true">
            <div class="modal-dialog" role="document">
                <div class="modal-content">
                    <div class="modal-header">
                        <h5 class="modal-title" id="staticBackdropLabel">Edit Barang</h5>
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                    </div>
                        <div class="modal-body">
                            @csrf
                            @method('PUT')
                            <div class="card-body">
                                {{ $dta->transaksiPembelianBarang->harga_satuan }}
                            </div>
                            <!-- /.card-body -->
                        </div>
                        <div class="modal-footer">
                            <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                            <button type="submit" class="btn btn-primary">Update</button>
                        </div>
                </div>
            </div>
        </div>
    @endforeach  --}}
@endsection

@push('scripts')
    {{-- DataTable --}}
    {{-- <script src="https://code.jquery.com/jquery-3.5.1.js"></script>
    <script src="https://cdn.datatables.net/1.11.5/js/jquery.dataTables.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.18.1/moment.min.js"></script>
    <script src="https://cdn.datatables.net/datetime/1.1.2/js/dataTables.dateTime.min.js"></script>

    <script src="https://cdn.datatables.net/buttons/2.2.2/js/dataTables.buttons.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jszip/3.1.3/jszip.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.53/pdfmake.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.53/vfs_fonts.js"></script>
    <script src="https://cdn.datatables.net/buttons/2.2.2/js/buttons.html5.min.js"></script>
    <script src="https://cdn.datatables.net/buttons/2.2.2/js/buttons.print.min.js"></script> --}}


    <script src=" {{ asset('assets/vendor/datatables/jquery.dataTables.min.js') }} "></script>
    <script src="{{ asset('assets/vendor/datatables/dataTables.bootstrap4.min.js') }} "></script>

    <!-- Page level custom scripts -->
    <script src="{{ asset('assets/js/demo/datatables-demo.js') }} "></script>

    <script>
        $(document).ready(function() {
            // DataTables initialisation
            // var table = $('#example').DataTable();
        });
    </script>
@endpush

resources/views/page/daftar-transaksi/index.blade.php
@extends('layouts.app')

@section('title', 'Master Barang')

@section('content')

    <div class="card shadow mb-4">
        <div class="card-header py-3">
            <h6 class="m-0 font-weight-bold text-primary" >Tabel Data Transaksi</h6>
        </div>
        <div class="card-body">
            <div class="table-responsive">
                <table id="dataTable" class="table table-bordered" style="width:100%">
                    <thead>
                        <tr>
                            <th>No</th>
                            <th>Waktu Pembelian</th>
                            <th>Total Harga</th>
                            <th class="text-center">Action</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach ($daftarTransaksi as $key => $data )
                            <tr>
                                <td>{{ $key + 1 }}</td>
                                <td>{{ Carbon\Carbon::parse($data->created_at)->translatedFormat('l, d F Y H:i') }}</td>
                                <td class="text-right">Rp.  {{number_format($data->total_harga,0,',','.')  }}</td>
                                <td class="text-center">
                                    <div class="form-inline justify-content-center">
                                        <a href="{{ route('daftar-transaksi.show', $data->id) }}" class="btn btn-primary btn-sm mr-1">Detail</a>
                                        <a href="{{ route('cetak', $data->id) }}" class="btn btn-info btn-sm mr-1">Cetak</a>
                                    </div>
                                </td>
                            </tr>
                        @endforeach
                    </tbody>
                </table>
            </div>
        </div>
    </div>


@endsection

resources/views/page/daftar-transaksi/print.blade.php
<!DOCTYPE html>
<html>
<head>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

    <title>Cetak Data Transaksi</title>

    <style>
        table.table-bordered > thead > tr > th{
            border:1px solid black;
        }
        table.table-bordered > tbody > tr > td{
            border:1px solid black;
        }
        table.table-bordered > tfoot > tr > td{
            border:1px solid black;
        }
    </style>
</head>
<body>
    <h1>{{ $title }}</h1>
    <p>{{ $date }}</p>
    <div class="table-responsive">
        <table id="dataTable" class="table table-bordered table-sm" style="width:100%;">
            <thead>
                <tr>
                    <th class="text-center">No</th>
                    <th class="text-center">Waktu Pembelian</th>
                    <th class="text-center">Nama Barang</th>
                    <th class="text-center">Jumlah</th>
                    <th class="text-center">Harga Satuan</th>
                    <th class="text-center">Total</th>

                </tr>
            </thead>
            <tbody>
                @foreach ($dataTransaksi as $key => $data )
                    <tr>
                        <td class="text-center">{{ $key + 1 }}</td>
                        <td>{{ Carbon\Carbon::parse($data->created_at)->translatedFormat('l, d F Y H:i') }}</td>
                        <td>{{ $data->masterBarang->nama_barang }}</td>
                        <td class="text-center">{{ $data->jumlah }}</td>
                        <td class="text-right">Rp  {{number_format($data->masterBarang->harga_satuan,0,',','.')  }}</td>
                        <td class="text-right">Rp {{ number_format($data->jumlah * $data->masterBarang->harga_satuan,0,',','.') }} </td>
                    </tr>
                @endforeach
            </tbody>
            <tfoot>
                <tr>
                    <td class="text-center font-weight-bold" colspan="5"> Total Transaksi</td>
                    <td class="text-right font-weight-bold">Rp {{ number_format($totalHarga->total_harga,0,',','.') }}</td>
                </tr>
            </tfoot>
        </table>
    </div>
</body>
</html>